// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function E停止服务器():Promise<string>;

export function E写到文件(arg1:string,arg2:string):Promise<void>;

export function E启动服务器(arg1:string):Promise<string>;

export function E检查更新():Promise<string>;

export function E读入文本(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;
