// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function E停止服务器() {
  return window['go']['main']['App']['E停止服务器']();
}

export function E写到文件(arg1, arg2) {
  return window['go']['main']['App']['E写到文件'](arg1, arg2);
}

export function E取运行目录() {
  return window['go']['main']['App']['E取运行目录']();
}

export function E启动服务器(arg1) {
  return window['go']['main']['App']['E启动服务器'](arg1);
}

export function E检查更新() {
  return window['go']['main']['App']['E检查更新']();
}

export function E读入文本(arg1) {
  return window['go']['main']['App']['E读入文本'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}
